#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
#add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get -y install haproxy
echo "frontend http-front
        bind *:80
        mode http
        default_backend http_roundrobin

backend http_roundrobin
        balance roundrobin
        server 38081-web-01 100.27.49.224:80 check
        server 38081-web-02 54.146.91.191:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start

